import { Suspense } from 'react';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import dynamic from 'next/dynamic';

// ******* Local Imports *******
import '../styles/globals.css';
const DynamicNavigation = dynamic(() => import('./components/navigation'));
const DynamicFooter = dynamic(() => import('./components/footer'));

export const metadata = {
  title: 'Devorbis | Software Development',
  description: 'Generated by Devorbis',
  icons: {
    icon: '/assets/images/favicon-32x32.png',
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='container relative' style={{ maxWidth: '1600px', width: '100%' }}>
          <DynamicNavigation />
        </div>
        <Suspense fallback={<div className="w-screen h-screen flex justify-center items-center"><div className='border-4 w-12 h-12 mx-4 border-dashed rounded-full animate-spin'/></div>}>
          {children}
        </Suspense>
        <div>
          <DynamicFooter />
        </div>
        <ToastContainer
          position="top-center"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
      </body>
    </html>
  );
}
